# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from opencv_apps/Face.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import opencv_apps.msg

class Face(genpy.Message):
  _md5sum = "0c2547d2eaf71219898bf5c25e36907e"
  _type = "opencv_apps/Face"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Rect face
Rect[] eyes

================================================================================
MSG: opencv_apps/Rect
# opencv Rect data type, x-y is center point
float64 x
float64 y
float64 width
float64 height

"""
  __slots__ = ['face','eyes']
  _slot_types = ['opencv_apps/Rect','opencv_apps/Rect[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       face,eyes

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Face, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.face is None:
        self.face = opencv_apps.msg.Rect()
      if self.eyes is None:
        self.eyes = []
    else:
      self.face = opencv_apps.msg.Rect()
      self.eyes = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4d.pack(_x.face.x, _x.face.y, _x.face.width, _x.face.height))
      length = len(self.eyes)
      buff.write(_struct_I.pack(length))
      for val1 in self.eyes:
        _x = val1
        buff.write(_struct_4d.pack(_x.x, _x.y, _x.width, _x.height))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.face is None:
        self.face = opencv_apps.msg.Rect()
      if self.eyes is None:
        self.eyes = None
      end = 0
      _x = self
      start = end
      end += 32
      (_x.face.x, _x.face.y, _x.face.width, _x.face.height,) = _struct_4d.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.eyes = []
      for i in range(0, length):
        val1 = opencv_apps.msg.Rect()
        _x = val1
        start = end
        end += 32
        (_x.x, _x.y, _x.width, _x.height,) = _struct_4d.unpack(str[start:end])
        self.eyes.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4d.pack(_x.face.x, _x.face.y, _x.face.width, _x.face.height))
      length = len(self.eyes)
      buff.write(_struct_I.pack(length))
      for val1 in self.eyes:
        _x = val1
        buff.write(_struct_4d.pack(_x.x, _x.y, _x.width, _x.height))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.face is None:
        self.face = opencv_apps.msg.Rect()
      if self.eyes is None:
        self.eyes = None
      end = 0
      _x = self
      start = end
      end += 32
      (_x.face.x, _x.face.y, _x.face.width, _x.face.height,) = _struct_4d.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.eyes = []
      for i in range(0, length):
        val1 = opencv_apps.msg.Rect()
        _x = val1
        start = end
        end += 32
        (_x.x, _x.y, _x.width, _x.height,) = _struct_4d.unpack(str[start:end])
        self.eyes.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4d = struct.Struct("<4d")
