set(_CATKIN_CURRENT_PACKAGE "ros_gpio")
set(ros_gpio_VERSION "0.0.4")
set(ros_gpio_MAINTAINER "Kenta Yonekura <yoneken@ieee.org>")
set(ros_gpio_PACKAGE_FORMAT "1")
set(ros_gpio_BUILD_DEPENDS "roscpp" "message_generation")
set(ros_gpio_BUILD_EXPORT_DEPENDS "roscpp" "message_runtime")
set(ros_gpio_BUILDTOOL_DEPENDS "catkin")
set(ros_gpio_BUILDTOOL_EXPORT_DEPENDS )
set(ros_gpio_EXEC_DEPENDS "roscpp" "message_runtime")
set(ros_gpio_RUN_DEPENDS "roscpp" "message_runtime")
set(ros_gpio_TEST_DEPENDS )
set(ros_gpio_DOC_DEPENDS )
set(ros_gpio_DEPRECATED "")