// Generated by gencpp from file ros_gpio/CloseUart.msg
// DO NOT EDIT!


#ifndef ROS_GPIO_MESSAGE_CLOSEUART_H
#define ROS_GPIO_MESSAGE_CLOSEUART_H

#include <ros/service_traits.h>


#include <ros_gpio/CloseUartRequest.h>
#include <ros_gpio/CloseUartResponse.h>


namespace ros_gpio
{

struct CloseUart
{

typedef CloseUartRequest Request;
typedef CloseUartResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CloseUart
} // namespace ros_gpio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_gpio::CloseUart > {
  static const char* value()
  {
    return "09a5a8266af8d6f25a1d421823e44e03";
  }

  static const char* value(const ::ros_gpio::CloseUart&) { return value(); }
};

template<>
struct DataType< ::ros_gpio::CloseUart > {
  static const char* value()
  {
    return "ros_gpio/CloseUart";
  }

  static const char* value(const ::ros_gpio::CloseUart&) { return value(); }
};


// service_traits::MD5Sum< ::ros_gpio::CloseUartRequest> should match 
// service_traits::MD5Sum< ::ros_gpio::CloseUart > 
template<>
struct MD5Sum< ::ros_gpio::CloseUartRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::CloseUart >::value();
  }
  static const char* value(const ::ros_gpio::CloseUartRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::CloseUartRequest> should match 
// service_traits::DataType< ::ros_gpio::CloseUart > 
template<>
struct DataType< ::ros_gpio::CloseUartRequest>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::CloseUart >::value();
  }
  static const char* value(const ::ros_gpio::CloseUartRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_gpio::CloseUartResponse> should match 
// service_traits::MD5Sum< ::ros_gpio::CloseUart > 
template<>
struct MD5Sum< ::ros_gpio::CloseUartResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::CloseUart >::value();
  }
  static const char* value(const ::ros_gpio::CloseUartResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::CloseUartResponse> should match 
// service_traits::DataType< ::ros_gpio::CloseUart > 
template<>
struct DataType< ::ros_gpio::CloseUartResponse>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::CloseUart >::value();
  }
  static const char* value(const ::ros_gpio::CloseUartResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_GPIO_MESSAGE_CLOSEUART_H
