// Generated by gencpp from file ros_gpio/ClosePwm.msg
// DO NOT EDIT!


#ifndef ROS_GPIO_MESSAGE_CLOSEPWM_H
#define ROS_GPIO_MESSAGE_CLOSEPWM_H

#include <ros/service_traits.h>


#include <ros_gpio/ClosePwmRequest.h>
#include <ros_gpio/ClosePwmResponse.h>


namespace ros_gpio
{

struct ClosePwm
{

typedef ClosePwmRequest Request;
typedef ClosePwmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClosePwm
} // namespace ros_gpio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_gpio::ClosePwm > {
  static const char* value()
  {
    return "09a5a8266af8d6f25a1d421823e44e03";
  }

  static const char* value(const ::ros_gpio::ClosePwm&) { return value(); }
};

template<>
struct DataType< ::ros_gpio::ClosePwm > {
  static const char* value()
  {
    return "ros_gpio/ClosePwm";
  }

  static const char* value(const ::ros_gpio::ClosePwm&) { return value(); }
};


// service_traits::MD5Sum< ::ros_gpio::ClosePwmRequest> should match 
// service_traits::MD5Sum< ::ros_gpio::ClosePwm > 
template<>
struct MD5Sum< ::ros_gpio::ClosePwmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::ClosePwm >::value();
  }
  static const char* value(const ::ros_gpio::ClosePwmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::ClosePwmRequest> should match 
// service_traits::DataType< ::ros_gpio::ClosePwm > 
template<>
struct DataType< ::ros_gpio::ClosePwmRequest>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::ClosePwm >::value();
  }
  static const char* value(const ::ros_gpio::ClosePwmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_gpio::ClosePwmResponse> should match 
// service_traits::MD5Sum< ::ros_gpio::ClosePwm > 
template<>
struct MD5Sum< ::ros_gpio::ClosePwmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::ClosePwm >::value();
  }
  static const char* value(const ::ros_gpio::ClosePwmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::ClosePwmResponse> should match 
// service_traits::DataType< ::ros_gpio::ClosePwm > 
template<>
struct DataType< ::ros_gpio::ClosePwmResponse>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::ClosePwm >::value();
  }
  static const char* value(const ::ros_gpio::ClosePwmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_GPIO_MESSAGE_CLOSEPWM_H
