// Generated by gencpp from file ros_gpio/GpioState.msg
// DO NOT EDIT!


#ifndef ROS_GPIO_MESSAGE_GPIOSTATE_H
#define ROS_GPIO_MESSAGE_GPIOSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ros_gpio
{
template <class ContainerAllocator>
struct GpioState_
{
  typedef GpioState_<ContainerAllocator> Type;

  GpioState_()
    : header()
    , pin(0)
    , value(0)  {
    }
  GpioState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pin(0)
    , value(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _pin_type;
  _pin_type pin;

   typedef uint8_t _value_type;
  _value_type value;




  typedef boost::shared_ptr< ::ros_gpio::GpioState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_gpio::GpioState_<ContainerAllocator> const> ConstPtr;

}; // struct GpioState_

typedef ::ros_gpio::GpioState_<std::allocator<void> > GpioState;

typedef boost::shared_ptr< ::ros_gpio::GpioState > GpioStatePtr;
typedef boost::shared_ptr< ::ros_gpio::GpioState const> GpioStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_gpio::GpioState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_gpio::GpioState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_gpio

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'ros_gpio': ['/home/yutak/ros_ws/src/ros_gpio/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_gpio::GpioState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_gpio::GpioState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_gpio::GpioState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_gpio::GpioState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_gpio::GpioState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_gpio::GpioState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_gpio::GpioState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "63669a74df2fbbf347dcb1c5113aef63";
  }

  static const char* value(const ::ros_gpio::GpioState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x63669a74df2fbbf3ULL;
  static const uint64_t static_value2 = 0x47dcb1c5113aef63ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_gpio::GpioState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_gpio/GpioState";
  }

  static const char* value(const ::ros_gpio::GpioState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_gpio::GpioState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint8 pin\n\
uint8 value\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::ros_gpio::GpioState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_gpio::GpioState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pin);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GpioState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_gpio::GpioState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_gpio::GpioState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pin: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pin);
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_GPIO_MESSAGE_GPIOSTATE_H
