// Generated by gencpp from file ros_gpio/OpenPwm.msg
// DO NOT EDIT!


#ifndef ROS_GPIO_MESSAGE_OPENPWM_H
#define ROS_GPIO_MESSAGE_OPENPWM_H

#include <ros/service_traits.h>


#include <ros_gpio/OpenPwmRequest.h>
#include <ros_gpio/OpenPwmResponse.h>


namespace ros_gpio
{

struct OpenPwm
{

typedef OpenPwmRequest Request;
typedef OpenPwmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OpenPwm
} // namespace ros_gpio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_gpio::OpenPwm > {
  static const char* value()
  {
    return "09a5a8266af8d6f25a1d421823e44e03";
  }

  static const char* value(const ::ros_gpio::OpenPwm&) { return value(); }
};

template<>
struct DataType< ::ros_gpio::OpenPwm > {
  static const char* value()
  {
    return "ros_gpio/OpenPwm";
  }

  static const char* value(const ::ros_gpio::OpenPwm&) { return value(); }
};


// service_traits::MD5Sum< ::ros_gpio::OpenPwmRequest> should match 
// service_traits::MD5Sum< ::ros_gpio::OpenPwm > 
template<>
struct MD5Sum< ::ros_gpio::OpenPwmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::OpenPwm >::value();
  }
  static const char* value(const ::ros_gpio::OpenPwmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::OpenPwmRequest> should match 
// service_traits::DataType< ::ros_gpio::OpenPwm > 
template<>
struct DataType< ::ros_gpio::OpenPwmRequest>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::OpenPwm >::value();
  }
  static const char* value(const ::ros_gpio::OpenPwmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_gpio::OpenPwmResponse> should match 
// service_traits::MD5Sum< ::ros_gpio::OpenPwm > 
template<>
struct MD5Sum< ::ros_gpio::OpenPwmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::OpenPwm >::value();
  }
  static const char* value(const ::ros_gpio::OpenPwmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::OpenPwmResponse> should match 
// service_traits::DataType< ::ros_gpio::OpenPwm > 
template<>
struct DataType< ::ros_gpio::OpenPwmResponse>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::OpenPwm >::value();
  }
  static const char* value(const ::ros_gpio::OpenPwmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_GPIO_MESSAGE_OPENPWM_H
