// Generated by gencpp from file ros_gpio/ReadPwm.msg
// DO NOT EDIT!


#ifndef ROS_GPIO_MESSAGE_READPWM_H
#define ROS_GPIO_MESSAGE_READPWM_H

#include <ros/service_traits.h>


#include <ros_gpio/ReadPwmRequest.h>
#include <ros_gpio/ReadPwmResponse.h>


namespace ros_gpio
{

struct ReadPwm
{

typedef ReadPwmRequest Request;
typedef ReadPwmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReadPwm
} // namespace ros_gpio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_gpio::ReadPwm > {
  static const char* value()
  {
    return "354dacb149f02d0b643577e3f431fdb8";
  }

  static const char* value(const ::ros_gpio::ReadPwm&) { return value(); }
};

template<>
struct DataType< ::ros_gpio::ReadPwm > {
  static const char* value()
  {
    return "ros_gpio/ReadPwm";
  }

  static const char* value(const ::ros_gpio::ReadPwm&) { return value(); }
};


// service_traits::MD5Sum< ::ros_gpio::ReadPwmRequest> should match 
// service_traits::MD5Sum< ::ros_gpio::ReadPwm > 
template<>
struct MD5Sum< ::ros_gpio::ReadPwmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::ReadPwm >::value();
  }
  static const char* value(const ::ros_gpio::ReadPwmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::ReadPwmRequest> should match 
// service_traits::DataType< ::ros_gpio::ReadPwm > 
template<>
struct DataType< ::ros_gpio::ReadPwmRequest>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::ReadPwm >::value();
  }
  static const char* value(const ::ros_gpio::ReadPwmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_gpio::ReadPwmResponse> should match 
// service_traits::MD5Sum< ::ros_gpio::ReadPwm > 
template<>
struct MD5Sum< ::ros_gpio::ReadPwmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::ReadPwm >::value();
  }
  static const char* value(const ::ros_gpio::ReadPwmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::ReadPwmResponse> should match 
// service_traits::DataType< ::ros_gpio::ReadPwm > 
template<>
struct DataType< ::ros_gpio::ReadPwmResponse>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::ReadPwm >::value();
  }
  static const char* value(const ::ros_gpio::ReadPwmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_GPIO_MESSAGE_READPWM_H
