// Generated by gencpp from file ros_gpio/SetPwmDuty_percentRequest.msg
// DO NOT EDIT!


#ifndef ROS_GPIO_MESSAGE_SETPWMDUTY_PERCENTREQUEST_H
#define ROS_GPIO_MESSAGE_SETPWMDUTY_PERCENTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_gpio
{
template <class ContainerAllocator>
struct SetPwmDuty_percentRequest_
{
  typedef SetPwmDuty_percentRequest_<ContainerAllocator> Type;

  SetPwmDuty_percentRequest_()
    : pin(0)
    , period_ms(0)
    , percent(0.0)  {
    }
  SetPwmDuty_percentRequest_(const ContainerAllocator& _alloc)
    : pin(0)
    , period_ms(0)
    , percent(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _pin_type;
  _pin_type pin;

   typedef uint32_t _period_ms_type;
  _period_ms_type period_ms;

   typedef float _percent_type;
  _percent_type percent;




  typedef boost::shared_ptr< ::ros_gpio::SetPwmDuty_percentRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_gpio::SetPwmDuty_percentRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetPwmDuty_percentRequest_

typedef ::ros_gpio::SetPwmDuty_percentRequest_<std::allocator<void> > SetPwmDuty_percentRequest;

typedef boost::shared_ptr< ::ros_gpio::SetPwmDuty_percentRequest > SetPwmDuty_percentRequestPtr;
typedef boost::shared_ptr< ::ros_gpio::SetPwmDuty_percentRequest const> SetPwmDuty_percentRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_gpio::SetPwmDuty_percentRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_gpio::SetPwmDuty_percentRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_gpio

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'ros_gpio': ['/home/yutak/ros_ws/src/ros_gpio/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_gpio::SetPwmDuty_percentRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_gpio::SetPwmDuty_percentRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_gpio::SetPwmDuty_percentRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_gpio::SetPwmDuty_percentRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_gpio::SetPwmDuty_percentRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_gpio::SetPwmDuty_percentRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_gpio::SetPwmDuty_percentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b63411b4769adebafcfd9a5a13fefbf3";
  }

  static const char* value(const ::ros_gpio::SetPwmDuty_percentRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb63411b4769adebaULL;
  static const uint64_t static_value2 = 0xfcfd9a5a13fefbf3ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_gpio::SetPwmDuty_percentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_gpio/SetPwmDuty_percentRequest";
  }

  static const char* value(const ::ros_gpio::SetPwmDuty_percentRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_gpio::SetPwmDuty_percentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 pin\n\
uint32 period_ms\n\
float32 percent\n\
";
  }

  static const char* value(const ::ros_gpio::SetPwmDuty_percentRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_gpio::SetPwmDuty_percentRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pin);
      stream.next(m.period_ms);
      stream.next(m.percent);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPwmDuty_percentRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_gpio::SetPwmDuty_percentRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_gpio::SetPwmDuty_percentRequest_<ContainerAllocator>& v)
  {
    s << indent << "pin: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pin);
    s << indent << "period_ms: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.period_ms);
    s << indent << "percent: ";
    Printer<float>::stream(s, indent + "  ", v.percent);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_GPIO_MESSAGE_SETPWMDUTY_PERCENTREQUEST_H
