// Generated by gencpp from file ros_gpio/SetPwmPulseWidth.msg
// DO NOT EDIT!


#ifndef ROS_GPIO_MESSAGE_SETPWMPULSEWIDTH_H
#define ROS_GPIO_MESSAGE_SETPWMPULSEWIDTH_H

#include <ros/service_traits.h>


#include <ros_gpio/SetPwmPulseWidthRequest.h>
#include <ros_gpio/SetPwmPulseWidthResponse.h>


namespace ros_gpio
{

struct SetPwmPulseWidth
{

typedef SetPwmPulseWidthRequest Request;
typedef SetPwmPulseWidthResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPwmPulseWidth
} // namespace ros_gpio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_gpio::SetPwmPulseWidth > {
  static const char* value()
  {
    return "487036c83e332bf69c50f08dda36b7bc";
  }

  static const char* value(const ::ros_gpio::SetPwmPulseWidth&) { return value(); }
};

template<>
struct DataType< ::ros_gpio::SetPwmPulseWidth > {
  static const char* value()
  {
    return "ros_gpio/SetPwmPulseWidth";
  }

  static const char* value(const ::ros_gpio::SetPwmPulseWidth&) { return value(); }
};


// service_traits::MD5Sum< ::ros_gpio::SetPwmPulseWidthRequest> should match 
// service_traits::MD5Sum< ::ros_gpio::SetPwmPulseWidth > 
template<>
struct MD5Sum< ::ros_gpio::SetPwmPulseWidthRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::SetPwmPulseWidth >::value();
  }
  static const char* value(const ::ros_gpio::SetPwmPulseWidthRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::SetPwmPulseWidthRequest> should match 
// service_traits::DataType< ::ros_gpio::SetPwmPulseWidth > 
template<>
struct DataType< ::ros_gpio::SetPwmPulseWidthRequest>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::SetPwmPulseWidth >::value();
  }
  static const char* value(const ::ros_gpio::SetPwmPulseWidthRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_gpio::SetPwmPulseWidthResponse> should match 
// service_traits::MD5Sum< ::ros_gpio::SetPwmPulseWidth > 
template<>
struct MD5Sum< ::ros_gpio::SetPwmPulseWidthResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::SetPwmPulseWidth >::value();
  }
  static const char* value(const ::ros_gpio::SetPwmPulseWidthResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::SetPwmPulseWidthResponse> should match 
// service_traits::DataType< ::ros_gpio::SetPwmPulseWidth > 
template<>
struct DataType< ::ros_gpio::SetPwmPulseWidthResponse>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::SetPwmPulseWidth >::value();
  }
  static const char* value(const ::ros_gpio::SetPwmPulseWidthResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_GPIO_MESSAGE_SETPWMPULSEWIDTH_H
