// Generated by gencpp from file ros_gpio/StopPwm.msg
// DO NOT EDIT!


#ifndef ROS_GPIO_MESSAGE_STOPPWM_H
#define ROS_GPIO_MESSAGE_STOPPWM_H

#include <ros/service_traits.h>


#include <ros_gpio/StopPwmRequest.h>
#include <ros_gpio/StopPwmResponse.h>


namespace ros_gpio
{

struct StopPwm
{

typedef StopPwmRequest Request;
typedef StopPwmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopPwm
} // namespace ros_gpio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_gpio::StopPwm > {
  static const char* value()
  {
    return "09a5a8266af8d6f25a1d421823e44e03";
  }

  static const char* value(const ::ros_gpio::StopPwm&) { return value(); }
};

template<>
struct DataType< ::ros_gpio::StopPwm > {
  static const char* value()
  {
    return "ros_gpio/StopPwm";
  }

  static const char* value(const ::ros_gpio::StopPwm&) { return value(); }
};


// service_traits::MD5Sum< ::ros_gpio::StopPwmRequest> should match 
// service_traits::MD5Sum< ::ros_gpio::StopPwm > 
template<>
struct MD5Sum< ::ros_gpio::StopPwmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::StopPwm >::value();
  }
  static const char* value(const ::ros_gpio::StopPwmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::StopPwmRequest> should match 
// service_traits::DataType< ::ros_gpio::StopPwm > 
template<>
struct DataType< ::ros_gpio::StopPwmRequest>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::StopPwm >::value();
  }
  static const char* value(const ::ros_gpio::StopPwmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_gpio::StopPwmResponse> should match 
// service_traits::MD5Sum< ::ros_gpio::StopPwm > 
template<>
struct MD5Sum< ::ros_gpio::StopPwmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::StopPwm >::value();
  }
  static const char* value(const ::ros_gpio::StopPwmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::StopPwmResponse> should match 
// service_traits::DataType< ::ros_gpio::StopPwm > 
template<>
struct DataType< ::ros_gpio::StopPwmResponse>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::StopPwm >::value();
  }
  static const char* value(const ::ros_gpio::StopPwmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_GPIO_MESSAGE_STOPPWM_H
