// Generated by gencpp from file ros_gpio/WriteGpio.msg
// DO NOT EDIT!


#ifndef ROS_GPIO_MESSAGE_WRITEGPIO_H
#define ROS_GPIO_MESSAGE_WRITEGPIO_H

#include <ros/service_traits.h>


#include <ros_gpio/WriteGpioRequest.h>
#include <ros_gpio/WriteGpioResponse.h>


namespace ros_gpio
{

struct WriteGpio
{

typedef WriteGpioRequest Request;
typedef WriteGpioResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WriteGpio
} // namespace ros_gpio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_gpio::WriteGpio > {
  static const char* value()
  {
    return "745c2434a6adca63dd033d5eb53a0db9";
  }

  static const char* value(const ::ros_gpio::WriteGpio&) { return value(); }
};

template<>
struct DataType< ::ros_gpio::WriteGpio > {
  static const char* value()
  {
    return "ros_gpio/WriteGpio";
  }

  static const char* value(const ::ros_gpio::WriteGpio&) { return value(); }
};


// service_traits::MD5Sum< ::ros_gpio::WriteGpioRequest> should match 
// service_traits::MD5Sum< ::ros_gpio::WriteGpio > 
template<>
struct MD5Sum< ::ros_gpio::WriteGpioRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::WriteGpio >::value();
  }
  static const char* value(const ::ros_gpio::WriteGpioRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::WriteGpioRequest> should match 
// service_traits::DataType< ::ros_gpio::WriteGpio > 
template<>
struct DataType< ::ros_gpio::WriteGpioRequest>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::WriteGpio >::value();
  }
  static const char* value(const ::ros_gpio::WriteGpioRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_gpio::WriteGpioResponse> should match 
// service_traits::MD5Sum< ::ros_gpio::WriteGpio > 
template<>
struct MD5Sum< ::ros_gpio::WriteGpioResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::WriteGpio >::value();
  }
  static const char* value(const ::ros_gpio::WriteGpioResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::WriteGpioResponse> should match 
// service_traits::DataType< ::ros_gpio::WriteGpio > 
template<>
struct DataType< ::ros_gpio::WriteGpioResponse>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::WriteGpio >::value();
  }
  static const char* value(const ::ros_gpio::WriteGpioResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_GPIO_MESSAGE_WRITEGPIO_H
