// Generated by gencpp from file ros_gpio/OpenGpio.msg
// DO NOT EDIT!


#ifndef ROS_GPIO_MESSAGE_OPENGPIO_H
#define ROS_GPIO_MESSAGE_OPENGPIO_H

#include <ros/service_traits.h>


#include <ros_gpio/OpenGpioRequest.h>
#include <ros_gpio/OpenGpioResponse.h>


namespace ros_gpio
{

struct OpenGpio
{

typedef OpenGpioRequest Request;
typedef OpenGpioResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OpenGpio
} // namespace ros_gpio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_gpio::OpenGpio > {
  static const char* value()
  {
    return "09a5a8266af8d6f25a1d421823e44e03";
  }

  static const char* value(const ::ros_gpio::OpenGpio&) { return value(); }
};

template<>
struct DataType< ::ros_gpio::OpenGpio > {
  static const char* value()
  {
    return "ros_gpio/OpenGpio";
  }

  static const char* value(const ::ros_gpio::OpenGpio&) { return value(); }
};


// service_traits::MD5Sum< ::ros_gpio::OpenGpioRequest> should match 
// service_traits::MD5Sum< ::ros_gpio::OpenGpio > 
template<>
struct MD5Sum< ::ros_gpio::OpenGpioRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::OpenGpio >::value();
  }
  static const char* value(const ::ros_gpio::OpenGpioRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::OpenGpioRequest> should match 
// service_traits::DataType< ::ros_gpio::OpenGpio > 
template<>
struct DataType< ::ros_gpio::OpenGpioRequest>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::OpenGpio >::value();
  }
  static const char* value(const ::ros_gpio::OpenGpioRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_gpio::OpenGpioResponse> should match 
// service_traits::MD5Sum< ::ros_gpio::OpenGpio > 
template<>
struct MD5Sum< ::ros_gpio::OpenGpioResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::OpenGpio >::value();
  }
  static const char* value(const ::ros_gpio::OpenGpioResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::OpenGpioResponse> should match 
// service_traits::DataType< ::ros_gpio::OpenGpio > 
template<>
struct DataType< ::ros_gpio::OpenGpioResponse>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::OpenGpio >::value();
  }
  static const char* value(const ::ros_gpio::OpenGpioResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_GPIO_MESSAGE_OPENGPIO_H
