// Generated by gencpp from file ros_gpio/ReadGpio.msg
// DO NOT EDIT!


#ifndef ROS_GPIO_MESSAGE_READGPIO_H
#define ROS_GPIO_MESSAGE_READGPIO_H

#include <ros/service_traits.h>


#include <ros_gpio/ReadGpioRequest.h>
#include <ros_gpio/ReadGpioResponse.h>


namespace ros_gpio
{

struct ReadGpio
{

typedef ReadGpioRequest Request;
typedef ReadGpioResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReadGpio
} // namespace ros_gpio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_gpio::ReadGpio > {
  static const char* value()
  {
    return "09a5a8266af8d6f25a1d421823e44e03";
  }

  static const char* value(const ::ros_gpio::ReadGpio&) { return value(); }
};

template<>
struct DataType< ::ros_gpio::ReadGpio > {
  static const char* value()
  {
    return "ros_gpio/ReadGpio";
  }

  static const char* value(const ::ros_gpio::ReadGpio&) { return value(); }
};


// service_traits::MD5Sum< ::ros_gpio::ReadGpioRequest> should match 
// service_traits::MD5Sum< ::ros_gpio::ReadGpio > 
template<>
struct MD5Sum< ::ros_gpio::ReadGpioRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::ReadGpio >::value();
  }
  static const char* value(const ::ros_gpio::ReadGpioRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::ReadGpioRequest> should match 
// service_traits::DataType< ::ros_gpio::ReadGpio > 
template<>
struct DataType< ::ros_gpio::ReadGpioRequest>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::ReadGpio >::value();
  }
  static const char* value(const ::ros_gpio::ReadGpioRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_gpio::ReadGpioResponse> should match 
// service_traits::MD5Sum< ::ros_gpio::ReadGpio > 
template<>
struct MD5Sum< ::ros_gpio::ReadGpioResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::ReadGpio >::value();
  }
  static const char* value(const ::ros_gpio::ReadGpioResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::ReadGpioResponse> should match 
// service_traits::DataType< ::ros_gpio::ReadGpio > 
template<>
struct DataType< ::ros_gpio::ReadGpioResponse>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::ReadGpio >::value();
  }
  static const char* value(const ::ros_gpio::ReadGpioResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_GPIO_MESSAGE_READGPIO_H
