// Generated by gencpp from file ros_gpio/SetPwmDuty_ms.msg
// DO NOT EDIT!


#ifndef ROS_GPIO_MESSAGE_SETPWMDUTY_MS_H
#define ROS_GPIO_MESSAGE_SETPWMDUTY_MS_H

#include <ros/service_traits.h>


#include <ros_gpio/SetPwmDuty_msRequest.h>
#include <ros_gpio/SetPwmDuty_msResponse.h>


namespace ros_gpio
{

struct SetPwmDuty_ms
{

typedef SetPwmDuty_msRequest Request;
typedef SetPwmDuty_msResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPwmDuty_ms
} // namespace ros_gpio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_gpio::SetPwmDuty_ms > {
  static const char* value()
  {
    return "5a9bd1f3e5e9225eb0777aa4e481be28";
  }

  static const char* value(const ::ros_gpio::SetPwmDuty_ms&) { return value(); }
};

template<>
struct DataType< ::ros_gpio::SetPwmDuty_ms > {
  static const char* value()
  {
    return "ros_gpio/SetPwmDuty_ms";
  }

  static const char* value(const ::ros_gpio::SetPwmDuty_ms&) { return value(); }
};


// service_traits::MD5Sum< ::ros_gpio::SetPwmDuty_msRequest> should match 
// service_traits::MD5Sum< ::ros_gpio::SetPwmDuty_ms > 
template<>
struct MD5Sum< ::ros_gpio::SetPwmDuty_msRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::SetPwmDuty_ms >::value();
  }
  static const char* value(const ::ros_gpio::SetPwmDuty_msRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::SetPwmDuty_msRequest> should match 
// service_traits::DataType< ::ros_gpio::SetPwmDuty_ms > 
template<>
struct DataType< ::ros_gpio::SetPwmDuty_msRequest>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::SetPwmDuty_ms >::value();
  }
  static const char* value(const ::ros_gpio::SetPwmDuty_msRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_gpio::SetPwmDuty_msResponse> should match 
// service_traits::MD5Sum< ::ros_gpio::SetPwmDuty_ms > 
template<>
struct MD5Sum< ::ros_gpio::SetPwmDuty_msResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::SetPwmDuty_ms >::value();
  }
  static const char* value(const ::ros_gpio::SetPwmDuty_msResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::SetPwmDuty_msResponse> should match 
// service_traits::DataType< ::ros_gpio::SetPwmDuty_ms > 
template<>
struct DataType< ::ros_gpio::SetPwmDuty_msResponse>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::SetPwmDuty_ms >::value();
  }
  static const char* value(const ::ros_gpio::SetPwmDuty_msResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_GPIO_MESSAGE_SETPWMDUTY_MS_H
