// Generated by gencpp from file ros_gpio/SetPwmDuty_percent.msg
// DO NOT EDIT!


#ifndef ROS_GPIO_MESSAGE_SETPWMDUTY_PERCENT_H
#define ROS_GPIO_MESSAGE_SETPWMDUTY_PERCENT_H

#include <ros/service_traits.h>


#include <ros_gpio/SetPwmDuty_percentRequest.h>
#include <ros_gpio/SetPwmDuty_percentResponse.h>


namespace ros_gpio
{

struct SetPwmDuty_percent
{

typedef SetPwmDuty_percentRequest Request;
typedef SetPwmDuty_percentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPwmDuty_percent
} // namespace ros_gpio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_gpio::SetPwmDuty_percent > {
  static const char* value()
  {
    return "c795464c6101769899fab4edd93f315f";
  }

  static const char* value(const ::ros_gpio::SetPwmDuty_percent&) { return value(); }
};

template<>
struct DataType< ::ros_gpio::SetPwmDuty_percent > {
  static const char* value()
  {
    return "ros_gpio/SetPwmDuty_percent";
  }

  static const char* value(const ::ros_gpio::SetPwmDuty_percent&) { return value(); }
};


// service_traits::MD5Sum< ::ros_gpio::SetPwmDuty_percentRequest> should match 
// service_traits::MD5Sum< ::ros_gpio::SetPwmDuty_percent > 
template<>
struct MD5Sum< ::ros_gpio::SetPwmDuty_percentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::SetPwmDuty_percent >::value();
  }
  static const char* value(const ::ros_gpio::SetPwmDuty_percentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::SetPwmDuty_percentRequest> should match 
// service_traits::DataType< ::ros_gpio::SetPwmDuty_percent > 
template<>
struct DataType< ::ros_gpio::SetPwmDuty_percentRequest>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::SetPwmDuty_percent >::value();
  }
  static const char* value(const ::ros_gpio::SetPwmDuty_percentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_gpio::SetPwmDuty_percentResponse> should match 
// service_traits::MD5Sum< ::ros_gpio::SetPwmDuty_percent > 
template<>
struct MD5Sum< ::ros_gpio::SetPwmDuty_percentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::SetPwmDuty_percent >::value();
  }
  static const char* value(const ::ros_gpio::SetPwmDuty_percentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::SetPwmDuty_percentResponse> should match 
// service_traits::DataType< ::ros_gpio::SetPwmDuty_percent > 
template<>
struct DataType< ::ros_gpio::SetPwmDuty_percentResponse>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::SetPwmDuty_percent >::value();
  }
  static const char* value(const ::ros_gpio::SetPwmDuty_percentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_GPIO_MESSAGE_SETPWMDUTY_PERCENT_H
