// Generated by gencpp from file ros_gpio/SetPwmDuty_percentResponse.msg
// DO NOT EDIT!


#ifndef ROS_GPIO_MESSAGE_SETPWMDUTY_PERCENTRESPONSE_H
#define ROS_GPIO_MESSAGE_SETPWMDUTY_PERCENTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_gpio
{
template <class ContainerAllocator>
struct SetPwmDuty_percentResponse_
{
  typedef SetPwmDuty_percentResponse_<ContainerAllocator> Type;

  SetPwmDuty_percentResponse_()
    : result(0)  {
    }
  SetPwmDuty_percentResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;




  typedef boost::shared_ptr< ::ros_gpio::SetPwmDuty_percentResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_gpio::SetPwmDuty_percentResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetPwmDuty_percentResponse_

typedef ::ros_gpio::SetPwmDuty_percentResponse_<std::allocator<void> > SetPwmDuty_percentResponse;

typedef boost::shared_ptr< ::ros_gpio::SetPwmDuty_percentResponse > SetPwmDuty_percentResponsePtr;
typedef boost::shared_ptr< ::ros_gpio::SetPwmDuty_percentResponse const> SetPwmDuty_percentResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_gpio::SetPwmDuty_percentResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_gpio::SetPwmDuty_percentResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_gpio

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'ros_gpio': ['/home/yutak/ros_ws/src/ros_gpio/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_gpio::SetPwmDuty_percentResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_gpio::SetPwmDuty_percentResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_gpio::SetPwmDuty_percentResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_gpio::SetPwmDuty_percentResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_gpio::SetPwmDuty_percentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_gpio::SetPwmDuty_percentResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_gpio::SetPwmDuty_percentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25458147911545c320c4c0a299eff763";
  }

  static const char* value(const ::ros_gpio::SetPwmDuty_percentResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25458147911545c3ULL;
  static const uint64_t static_value2 = 0x20c4c0a299eff763ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_gpio::SetPwmDuty_percentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_gpio/SetPwmDuty_percentResponse";
  }

  static const char* value(const ::ros_gpio::SetPwmDuty_percentResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_gpio::SetPwmDuty_percentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 result\n\
\n\
";
  }

  static const char* value(const ::ros_gpio::SetPwmDuty_percentResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_gpio::SetPwmDuty_percentResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPwmDuty_percentResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_gpio::SetPwmDuty_percentResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_gpio::SetPwmDuty_percentResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_GPIO_MESSAGE_SETPWMDUTY_PERCENTRESPONSE_H
