// Generated by gencpp from file ros_gpio/SetPwmPeriod.msg
// DO NOT EDIT!


#ifndef ROS_GPIO_MESSAGE_SETPWMPERIOD_H
#define ROS_GPIO_MESSAGE_SETPWMPERIOD_H

#include <ros/service_traits.h>


#include <ros_gpio/SetPwmPeriodRequest.h>
#include <ros_gpio/SetPwmPeriodResponse.h>


namespace ros_gpio
{

struct SetPwmPeriod
{

typedef SetPwmPeriodRequest Request;
typedef SetPwmPeriodResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPwmPeriod
} // namespace ros_gpio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_gpio::SetPwmPeriod > {
  static const char* value()
  {
    return "6402e67c22c9390eed6cabea0cd0db31";
  }

  static const char* value(const ::ros_gpio::SetPwmPeriod&) { return value(); }
};

template<>
struct DataType< ::ros_gpio::SetPwmPeriod > {
  static const char* value()
  {
    return "ros_gpio/SetPwmPeriod";
  }

  static const char* value(const ::ros_gpio::SetPwmPeriod&) { return value(); }
};


// service_traits::MD5Sum< ::ros_gpio::SetPwmPeriodRequest> should match 
// service_traits::MD5Sum< ::ros_gpio::SetPwmPeriod > 
template<>
struct MD5Sum< ::ros_gpio::SetPwmPeriodRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::SetPwmPeriod >::value();
  }
  static const char* value(const ::ros_gpio::SetPwmPeriodRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::SetPwmPeriodRequest> should match 
// service_traits::DataType< ::ros_gpio::SetPwmPeriod > 
template<>
struct DataType< ::ros_gpio::SetPwmPeriodRequest>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::SetPwmPeriod >::value();
  }
  static const char* value(const ::ros_gpio::SetPwmPeriodRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_gpio::SetPwmPeriodResponse> should match 
// service_traits::MD5Sum< ::ros_gpio::SetPwmPeriod > 
template<>
struct MD5Sum< ::ros_gpio::SetPwmPeriodResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::SetPwmPeriod >::value();
  }
  static const char* value(const ::ros_gpio::SetPwmPeriodResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::SetPwmPeriodResponse> should match 
// service_traits::DataType< ::ros_gpio::SetPwmPeriod > 
template<>
struct DataType< ::ros_gpio::SetPwmPeriodResponse>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::SetPwmPeriod >::value();
  }
  static const char* value(const ::ros_gpio::SetPwmPeriodResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_GPIO_MESSAGE_SETPWMPERIOD_H
