// Generated by gencpp from file ros_gpio/StartPwm.msg
// DO NOT EDIT!


#ifndef ROS_GPIO_MESSAGE_STARTPWM_H
#define ROS_GPIO_MESSAGE_STARTPWM_H

#include <ros/service_traits.h>


#include <ros_gpio/StartPwmRequest.h>
#include <ros_gpio/StartPwmResponse.h>


namespace ros_gpio
{

struct StartPwm
{

typedef StartPwmRequest Request;
typedef StartPwmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartPwm
} // namespace ros_gpio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_gpio::StartPwm > {
  static const char* value()
  {
    return "09a5a8266af8d6f25a1d421823e44e03";
  }

  static const char* value(const ::ros_gpio::StartPwm&) { return value(); }
};

template<>
struct DataType< ::ros_gpio::StartPwm > {
  static const char* value()
  {
    return "ros_gpio/StartPwm";
  }

  static const char* value(const ::ros_gpio::StartPwm&) { return value(); }
};


// service_traits::MD5Sum< ::ros_gpio::StartPwmRequest> should match 
// service_traits::MD5Sum< ::ros_gpio::StartPwm > 
template<>
struct MD5Sum< ::ros_gpio::StartPwmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::StartPwm >::value();
  }
  static const char* value(const ::ros_gpio::StartPwmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::StartPwmRequest> should match 
// service_traits::DataType< ::ros_gpio::StartPwm > 
template<>
struct DataType< ::ros_gpio::StartPwmRequest>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::StartPwm >::value();
  }
  static const char* value(const ::ros_gpio::StartPwmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_gpio::StartPwmResponse> should match 
// service_traits::MD5Sum< ::ros_gpio::StartPwm > 
template<>
struct MD5Sum< ::ros_gpio::StartPwmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::StartPwm >::value();
  }
  static const char* value(const ::ros_gpio::StartPwmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::StartPwmResponse> should match 
// service_traits::DataType< ::ros_gpio::StartPwm > 
template<>
struct DataType< ::ros_gpio::StartPwmResponse>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::StartPwm >::value();
  }
  static const char* value(const ::ros_gpio::StartPwmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_GPIO_MESSAGE_STARTPWM_H
