// Generated by gencpp from file ros_gpio/WritePwm.msg
// DO NOT EDIT!


#ifndef ROS_GPIO_MESSAGE_WRITEPWM_H
#define ROS_GPIO_MESSAGE_WRITEPWM_H

#include <ros/service_traits.h>


#include <ros_gpio/WritePwmRequest.h>
#include <ros_gpio/WritePwmResponse.h>


namespace ros_gpio
{

struct WritePwm
{

typedef WritePwmRequest Request;
typedef WritePwmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WritePwm
} // namespace ros_gpio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_gpio::WritePwm > {
  static const char* value()
  {
    return "a2df55be2706973ca3e6bece6c75ed9e";
  }

  static const char* value(const ::ros_gpio::WritePwm&) { return value(); }
};

template<>
struct DataType< ::ros_gpio::WritePwm > {
  static const char* value()
  {
    return "ros_gpio/WritePwm";
  }

  static const char* value(const ::ros_gpio::WritePwm&) { return value(); }
};


// service_traits::MD5Sum< ::ros_gpio::WritePwmRequest> should match 
// service_traits::MD5Sum< ::ros_gpio::WritePwm > 
template<>
struct MD5Sum< ::ros_gpio::WritePwmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::WritePwm >::value();
  }
  static const char* value(const ::ros_gpio::WritePwmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::WritePwmRequest> should match 
// service_traits::DataType< ::ros_gpio::WritePwm > 
template<>
struct DataType< ::ros_gpio::WritePwmRequest>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::WritePwm >::value();
  }
  static const char* value(const ::ros_gpio::WritePwmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_gpio::WritePwmResponse> should match 
// service_traits::MD5Sum< ::ros_gpio::WritePwm > 
template<>
struct MD5Sum< ::ros_gpio::WritePwmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_gpio::WritePwm >::value();
  }
  static const char* value(const ::ros_gpio::WritePwmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_gpio::WritePwmResponse> should match 
// service_traits::DataType< ::ros_gpio::WritePwm > 
template<>
struct DataType< ::ros_gpio::WritePwmResponse>
{
  static const char* value()
  {
    return DataType< ::ros_gpio::WritePwm >::value();
  }
  static const char* value(const ::ros_gpio::WritePwmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_GPIO_MESSAGE_WRITEPWM_H
