set(_CATKIN_CURRENT_PACKAGE "gaze_arm")
set(gaze_arm_VERSION "0.0.0")
set(gaze_arm_MAINTAINER "yoneken <yoneken@ieee.org>")
set(gaze_arm_PACKAGE_FORMAT "1")
set(gaze_arm_BUILD_DEPENDS "ros_gpio" "rospy" "teleop_twist_keyboard")
set(gaze_arm_BUILD_EXPORT_DEPENDS "ros_gpio" "rospy" "teleop_twist_keyboard")
set(gaze_arm_BUILDTOOL_DEPENDS "catkin")
set(gaze_arm_BUILDTOOL_EXPORT_DEPENDS )
set(gaze_arm_EXEC_DEPENDS "ros_gpio" "rospy" "teleop_twist_keyboard")
set(gaze_arm_RUN_DEPENDS "ros_gpio" "rospy" "teleop_twist_keyboard")
set(gaze_arm_TEST_DEPENDS )
set(gaze_arm_DOC_DEPENDS )
set(gaze_arm_DEPRECATED "")