serial_no: 38330151
cam_name: "narrow_stereo"
yaml_url: "package://ximea_camera/calibrations/camera1.yaml"
exposure_time: 30000
rect_left: 200
rect_top: 200
rect_height: 600
rect_width: 900
image_data_format: "XI_MONO8"
