// Generated by gencpp from file exp_excavator/JointCommand.msg
// DO NOT EDIT!


#ifndef EXP_EXCAVATOR_MESSAGE_JOINTCOMMAND_H
#define EXP_EXCAVATOR_MESSAGE_JOINTCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace exp_excavator
{
template <class ContainerAllocator>
struct JointCommand_
{
  typedef JointCommand_<ContainerAllocator> Type;

  JointCommand_()
    : header()
    , boomV(0.0)
    , armV(0.0)
    , bucketV(0.0)
    , swingV(0.0)
    , boomP(0.0)
    , armI(0.0)
    , Kmode(false)  {
    }
  JointCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , boomV(0.0)
    , armV(0.0)
    , bucketV(0.0)
    , swingV(0.0)
    , boomP(0.0)
    , armI(0.0)
    , Kmode(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _boomV_type;
  _boomV_type boomV;

   typedef double _armV_type;
  _armV_type armV;

   typedef double _bucketV_type;
  _bucketV_type bucketV;

   typedef double _swingV_type;
  _swingV_type swingV;

   typedef double _boomP_type;
  _boomP_type boomP;

   typedef double _armI_type;
  _armI_type armI;

   typedef uint8_t _Kmode_type;
  _Kmode_type Kmode;




  typedef boost::shared_ptr< ::exp_excavator::JointCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exp_excavator::JointCommand_<ContainerAllocator> const> ConstPtr;

}; // struct JointCommand_

typedef ::exp_excavator::JointCommand_<std::allocator<void> > JointCommand;

typedef boost::shared_ptr< ::exp_excavator::JointCommand > JointCommandPtr;
typedef boost::shared_ptr< ::exp_excavator::JointCommand const> JointCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exp_excavator::JointCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exp_excavator::JointCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace exp_excavator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'exp_excavator': ['/home/d-lab/ExcavatorROS.git/src/exp_excavator/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::exp_excavator::JointCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exp_excavator::JointCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exp_excavator::JointCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exp_excavator::JointCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exp_excavator::JointCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exp_excavator::JointCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exp_excavator::JointCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b10af80a7509e5ff22dd3595cefb8785";
  }

  static const char* value(const ::exp_excavator::JointCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb10af80a7509e5ffULL;
  static const uint64_t static_value2 = 0x22dd3595cefb8785ULL;
};

template<class ContainerAllocator>
struct DataType< ::exp_excavator::JointCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exp_excavator/JointCommand";
  }

  static const char* value(const ::exp_excavator::JointCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exp_excavator::JointCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float64 boomV\n\
float64 armV\n\
float64 bucketV\n\
float64 swingV\n\
float64 boomP\n\
float64 armI\n\
bool Kmode\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::exp_excavator::JointCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exp_excavator::JointCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.boomV);
      stream.next(m.armV);
      stream.next(m.bucketV);
      stream.next(m.swingV);
      stream.next(m.boomP);
      stream.next(m.armI);
      stream.next(m.Kmode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exp_excavator::JointCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exp_excavator::JointCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "boomV: ";
    Printer<double>::stream(s, indent + "  ", v.boomV);
    s << indent << "armV: ";
    Printer<double>::stream(s, indent + "  ", v.armV);
    s << indent << "bucketV: ";
    Printer<double>::stream(s, indent + "  ", v.bucketV);
    s << indent << "swingV: ";
    Printer<double>::stream(s, indent + "  ", v.swingV);
    s << indent << "boomP: ";
    Printer<double>::stream(s, indent + "  ", v.boomP);
    s << indent << "armI: ";
    Printer<double>::stream(s, indent + "  ", v.armI);
    s << indent << "Kmode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Kmode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXP_EXCAVATOR_MESSAGE_JOINTCOMMAND_H
